services:
  - redis-server

language: node_js
node_js:
  - "6"

before_script:
  - cd src/app/
  - npm install

script:
  - npm test

after_script:
  - NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec 
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - rm -rf ./coverage
