nginx:
    image: rxie25/nginx
    cpu_shares: 256
    mem_limit: 131072000
    ports:
        - "80:80"
    links:
        - "app1:app1"
        - "app2:app2"

app1:
    image: rxie25/tinyurl
    cpu_shares: 256
    mem_limit: 262144000
    ports:
        - "3000"
    links:
        - "cache:redis"

app2:
    image: rxie25/tinyurl
    cpu_shares: 256
    mem_limit: 262144000
    ports:
        - "3000"
    links:
        - "cache:redis"

cache:
    image: redis
    cpu_shares: 256
    mem_limit: 262144000